AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  DisplayCopNames: true

  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "Gemfile.lock"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'it']
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachForSimpleLoop:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/OptionalBooleanParameter:
  Exclude:
    - 'classes/music_album.rb'

Metrics/ParameterLists:
  Exclude:
    - 'classes/game.rb'