name: Linters

on:
  push:
  pull_request:

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v3
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop ---color