name: Linters

on:
  pull_request:

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
          cache-version: 2

      - run: bundle exec rubocop