name: Tests

on: pull_request

jobs:
  rspec:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v3
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec