name: Tests

on:
  pull_request:

jobs:
  rspec:
    name: RSpec Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v3
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec
        run: bundle exec rspec